user_1 = "Поладько Дмитрий"
user_2 = "Отдел Кадров"
user_3 = "Соболев Иван"
user_4 = "Кобякова Елена"
# login_1 = "poladko.dv"
# pass_1 = ""
login_2 = "OK_RLI"
pass_2 = "OK_RLIOK_RLI"
login_3 = "sobolev"
pass_3 = "sobolevsobolev"
login_4 = "kobiyakova"
pass_4 = "kobiyakovakobiyakova"
link = "https://intranet-test.roslesinforg.ru/stream/"
link_7 = "https://intranet-test.roslesinforg.ru/company/personal/user/26547/tasks/"
link_8 = "https://intranet-test.roslesinforg.ru/company/personal/user/26547/calendar/"
link_15 = "https://roslesinforg.ru/"
users = [user_1, user_2, user_3, user_4]
user_login = [login_2, login_3, login_4]  # список логинов для определения наибольшей длины из них (ТК 9)
user_password = [pass_2, pass_3, pass_4]